#!/bin/bash

# Define an associative array with the service names and descriptions
declare -A profiles=(
  ["ona"]="The ONA service"
  ["detection"]="The hybridaiobjectdetection service"
  ["tracking"]="The hybridaiobjecttracking service"
  ["text"]="The hybridaistreamingtext service"
  ["networking"]="The hybridainetworking service"
)

# Function to print the help message
print_help() {
  echo "Available profiles:"
  for profile in "${!profiles[@]}"; do
    echo "- $profile: ${profiles[$profile]}"
  done
}

# If no arguments or one of help options are provided, print the help message
if [[ $# -eq 0 ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]] || [[ $1 == "help" ]]; then
  print_help
else
  # Check if the argument is a valid profile
  if [[ -n ${profiles[$1]} ]]; then
    docker-compose --profile "$1" up
  else
    echo "Invalid profile: $1"
    print_help
    exit 1
  fi
fi
