---
- name: Run PostgreSQL and Nginx containers
  hosts: all
  become: yes

  tasks:
    - name: Run PostgreSQL container
      docker_container:
        name: postgres
        image: postgres
        state: started
        env:
          POSTGRES_PASSWORD: your_password
        ports:
          - "5432:5432"
        volumes:
          - /path/to/postgres/data:/var/lib/postgresql/data

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
        volumes:
          - /path/to/nginx/html:/usr/share/nginx/html
          - /path/to/nginx/conf:/etc/nginx
