# This workflow will install Python dependencies, run nno and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test coverage application

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Test with unittest
      run: |
        pip install coverage
        python -m unittest discover -s .
        coverage run -m unittest discover -s .
        coverage xml -i
    - name: Test coverage
      uses: orgoro/coverage@v3
      with:
        coverageFile: ./coverage.xml
        token: ${{ secrets.TOKEN}}
        thresholdAll: 70

